# Generated by Django 4.2.8 on 2023-12-22 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowings', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'pending'), ('PAID', 'paid'), ('EXPIRED', 'expired')], max_length=8)),
                ('type', models.CharField(blank=True, choices=[('PAYMENT ', 'payment'), ('FINE', 'fine')], max_length=8)),
                ('session_url', models.URLField(unique=True)),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('money_to_pay', models.DecimalField(decimal_places=2, max_digits=20)),
                ('borrowing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='borrowings.borrowing')),
            ],
        ),
    ]
